[theme]
name = "plain"

[theme.overrides]
separator = "··"
idle_fg = "#5f87af"

#[icons]
#name = "awesome"

[[block]]
block = "focused_window"
max_width = 50

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1


[[block]]
block = "sound"

[[block]]
block = "backlight"


[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
use_nag = true

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "{average}° avg"
chip = "*-isa-*"

[[block]]
block = "battery"
interval = 10
format = " {percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
